version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: mysql_db

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: spring_app

    ports:
      - "8080:8080"

    depends_on:
      - mysql

    environment:
      DB_ENDPOINT: mysql
      DB_PORT: 3306
      DB_NAME: bdd
      DB_USERNAME: root
      DB_PASSWORD: root

volumes:
  mysql_data: