#Despliegue
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend-innovatech:latest
          #no descargar la imagen desde Docker Hub, sinó que local.
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
#Service:
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      #Puerto expuesto en el nodo de kubernet:
      nodePort: 30080
  #NodePort: expone el servicio fuera de cluster kubernet:
  type: LoadBalancer #LoadBalancer: balanceador de carga de una red