name: Build and Deploy to EKS

on:
  push:
    branches:
      - develop

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER: innovatech-eks
  ECR_BACKEND_VENTAS: backend-ventas
  ECR_BACKEND_DESPACHOS: backend-despachos
  ECR_FRONTEND: frontend-despacho

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Backend Ventas
        run: |
          docker build \
          -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_BACKEND_VENTAS }}:latest \
          ./backend/back-Ventas_SpringBoot/Springboot-API-REST

      - name: Push Backend Ventas
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_BACKEND_VENTAS }}:latest

      - name: Build Backend Despachos
        run: |
          docker build \
          -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_BACKEND_DESPACHOS }}:latest \
          ./backend/back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO

      - name: Push Backend Despachos
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_BACKEND_DESPACHOS }}:latest

      - name: Build Frontend
        run: |
          docker build \
          -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_FRONTEND }}:latest \
          ./frontend/front_despacho

      - name: Push Frontend
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_FRONTEND }}:latest

      - name: Configurar kubectl
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $EKS_CLUSTER

      - name: Aplicar manifests Kubernetes
        run: |
          kubectl apply -f infra/k8s/

      - name: Reiniciar deployments
        run: |
          kubectl rollout restart deployment/backend-ventas
          kubectl rollout restart deployment/backend-despacho
          kubectl rollout restart deployment/frontend

      - name: Esperar rollout backend ventas
        run: |
          kubectl rollout status deployment/backend-ventas --timeout=300s

      - name: Esperar rollout backend despacho
        run: |
          kubectl rollout status deployment/backend-despacho --timeout=300s

      - name: Esperar rollout frontend
        run: |
          kubectl rollout status deployment/frontend --timeout=300s